inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails

## 全体に適応する項目を定義。ここで Exclude に設定したファイルは、チェック対象外になる。
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

Rails:
  Enabled: true

Rails/FilePath:
  Exclude:
    - 'spec/rails_helper.rb'

## 日本語コメントを許可する。
Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/CommentIndentation:
  Enabled: false

# https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutemptylinesaroundattributeaccessor
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# https://rubocop.readthedocs.io/en/stable/cops_layout/#layoutspacearoundmethodcalloperator
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

# https://rubocop.readthedocs.io/en/stable/cops_style/#styleblockdelimiters
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
  Exclude:
    - 'spec/**/*'

# ドキュメントの無いpublic classを許可する
Style/Documentation:
  Enabled: false


# trueかfalseを設定しないと警告が出る
# https://rubocop.readthedocs.io/en/stable/cops_style/#stylehasheachmethods
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# 条件式の方を意識させたい場合には後置の if/unless を使わない方が分かりやすい
Style/IfUnlessModifier:
  Enabled: false
